#! /usr/bin/env bash

### Init script for test suite's Docker container ###

MONGODB_PORT=27017
NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
VARIETY_DOCKER_DIR=/opt/variety

# Start MongoDB with disabled journaling and disabled logging
mongod --nojournal --logpath /dev/null &

cd $VARIETY_DOCKER_DIR || exit

npm install

while ! curl --silent http://localhost:$MONGODB_PORT > /dev/null 2>&1
do
  echo "Waiting for MongoDB connection…"
  sleep 1
done
echo "MongoDB ready"

npm run test:mocha
